name: "Terraform"

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print current directory
        run: pwd
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init
      - name: Validate Terraform configuration
        run: terraform validate
      - name: Format Terraform configuration
        run: terraform fmt -check
      - name: Plan Terraform changes
        run: terraform plan
